config/routes.rb
Winloss::Application.routes.draw do
  resources :games, :only => [:index, :create, :destroy]
  resources :users, :only => [:index], defaults: { format: 'json' }
  root :to => 'games#index'
end

app/models/game.rb
require 'parser'

class Game < ActiveRecord::Base
  belongs_to :winner, :class_name => 'User'
  belongs_to :loser, :class_name => 'User'

  validates :winner_id, :loser_id, :presence => true
  validates :winner_score, :loser_score, :presence => true
  validates :played_date, :presence => true

  scope :for_user, lambda { |user| where('winner_id = :user_id OR loser_id = :user_id', user_id: user.id) }

  def self.parse phrase
    GameCreator.new Parser.parse(phrase)
  end

  def self.parse! phrase
    parse(phrase).save!
  end

  def self.scores_for(user)
    for_user(user).select("(CASE WHEN winner_id = #{user.id} THEN winner_score ELSE loser_score END) as score").map { |game| game.score.to_i }
  end

  def winner_name
    winner.name
  end

  def loser_name
    loser.name
  end

  def as_json(options=nil)
    options[:only] = options[:methods] = []
    options[:only] << :winner_score
    options[:only] << :loser_score
    options[:only] << :played_date
    options[:methods] << :winner_name
    options[:methods] << :loser_name
    super(options)
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_and_belongs_to_many :users
  before_create :set_team_name

  def self.create_from_user_names(*names)
    create! :users => User.where(:name => names)
  end

  def set_team_name
    self.name ||= self.users.map(&:name).sort.join(' + ')
  end

  def games
    TeamGame.for_team(self)
  end

  def points_per_game
    scores.empty? ? 0 : scores.reduce(0, :+).to_f / scores.length
  end

  def scores
    connection.select_rows(<<-SQL
      SELECT    (CASE WHEN winner_id = #{self.id} THEN winner_score ELSE loser_score END) as score
      FROM      team_games
      WHERE     winner_id = #{self.id}
      OR        loser_id = #{self.id}
    SQL
    ).flatten.map(&:to_i)
  end
end

app/models/team_game.rb
require 'parser'

class TeamGame < ActiveRecord::Base
  belongs_to :winner, :class_name => 'Team'
  belongs_to :loser, :class_name => 'Team'

  validates :winner_id, :loser_id, :presence => true
  validates :winner_score, :loser_score, :presence => true
  validates :played_date, :presence => true

  scope :for_team, lambda { |team| where("winner_id = #{team.id} OR loser_id = #{team.id}") }

  def self.parse phrase
    TeamGameCreator.new Parser.parse(phrase)
  end

  def self.parse! phrase
    parse(phrase).save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :teams
  validates :name, presence: true, uniqueness: true

  def self.top_ranked(count=nil)
    users = all.sort {|x,y| y.points_per_game <=> x.points_per_game }
    users = users.first(count) if count
    users
  end

  def games
    Game.for_user(self)
  end

  def points_per_game
    scores.empty? ? 0 : scores.reduce(0, :+).to_f / scores.length
  end

  def scores
    games.scores_for(self)
  end

  def to_s
    name
  end

  def as_json(options)
    options[:only] = []
    options[:only] << :name
    options[:methods] = []
    options[:methods] << :points_per_game
    super(options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html, :json

  def index
    count = params[:count] || 5
    @games = Game.last(count.to_i).reverse
    respond_with({:games => @games})
  end

  def create
    game = case params[:game_type]
    when 'Individual'
      Game.parse(params[:result])
    when 'Team'
      TeamGame.parse(params[:result])
    end

    if game && game.save
      redirect_to root_path, :notice => t(:valid_game)
    else
      redirect_to root_path, :alert => t(:invalid_game)
    end
  end

  def destroy
    game = Game.find params[:id]
    game.destroy

    redirect_to root_path, :notice => t(:game_destroyed)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json
  def index
    count = params[:count]
    respond_with({:users => User.top_ranked((count && count.to_i))})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages_for(*types)
    types.map do |type|
      content_tag :div, {:class => "alert alert-block alert-#{type}"}, false do
        close_link = content_tag :a, raw('&times;'), {:class => 'close', :'data-dismiss' => 'alert'}
        close_link + content_tag(:div, flash[type], {:class => "container"}, false)
      end if flash[type].present?
    end.compact.join.html_safe
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def game_entry(game, destroy=false)
    content_tag :li, :class => 'game', :id => dom_id(game) do
      content = content_tag :span, game.winner, :class => 'winner'
      content += ' beat '
      content += content_tag :span, game.loser, :class => 'loser'
      content += ' '
      content += content_tag :span, "#{game.winner_score}-#{game.loser_score}", :class => 'score'
      content += ' on '
      content += content_tag :span, game.played_date, :class => 'game_date'
      if destroy
        link = link_to(raw('&times;'), game_path(game), :confirm => 'Are you sure?', :method => :delete)
        content += content_tag :span, link, :class => 'delete'
      end
      content
    end
  end

  def ranking_for(user, date_range)
    games = date_range ? Game.where(played_date: date_range) : Game.scoped
    scores = games.scores_for(user)
    if scores.present?
      content = content_tag :span, number_with_precision(points_per_game(scores), precision: 2), :class => 'points-per-game'
      content += ' / '
      content += content_tag :span, scores.count, :class => 'count'
      content
    else
      content_tag :span, '--', :class => 'points-per-game'
    end
  end

  def points_per_game(scores)
    scores.empty? ? 0 : scores.reduce(0, :+).to_f / scores.length
  end
end

app/views/games/_leaderboard.html.haml
%h2 Leaderboard
%table.table.table-striped
  %thead
    %tr
      %th.user
      %th.this-week This Week
      %th.this-month This Month
      %th.all-time All Time
  %tbody
    - User.top_ranked.each do |user|
      %tr[user]
        %td.user
          = user.name
        %td.this-week.ranking
          = ranking_for user, (Date.today.beginning_of_week..Date.today)
        %td.this-month.ranking
          = ranking_for user, (Date.today.beginning_of_month..Date.today.end_of_month)
        %td.all-time.ranking
          = ranking_for user, nil

app/views/games/_team_leaderboard.html.haml
%h2 Team Leaderboard
%table.table.table-striped
  %tbody
    - Team.all.sort {|x,y| y.points_per_game <=> x.points_per_game }.each do |team|
      %tr[team]
        %td.team= team.name
        %td.ranking
          - if team.points_per_game > 0
            %span.points-per-game
              = number_with_precision team.points_per_game, precision: 2
            %span.count
              over
              = TeamGame.for_team(team).count
              games
          - else
            %span.points_per_game
              \--

app/views/games/index.html.haml
%section#leaderboard
  = render 'leaderboard'
  = render 'team_leaderboard' if Team.all.present?

%section#recent
  %h2 Recent Games
  %ul#last-games
    - @games.each_with_index do |game, i|
      = game_entry game, i == 0

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title WinLoss.
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      .container
        %hgroup
          %h1 Win-Loss
          %h2 Record ass-whoopings.

      = flash_messages_for :notice, :alert, :message

    .container
      %section#entry
        = form_tag games_path do |f|
          = text_field_tag :result, nil, placeholder: 'Record your result', autofocus: true
          = select_tag 'game_type', '<option>Individual</option><option>Team</option>'.html_safe
          = submit_tag 'Record', :class => 'btn btn-primary'

      = yield